name: hiervae
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - binutils_impl_linux-64=2.40=hf600244_0
  - boost=1.70.0=py37h9de70de_1
  - boost-cpp=1.70.0=h8e57a91_2
  - bottleneck=1.3.5=py37hda87dfa_0
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2022.12.7=pyhd8ed1ab_0
  - expat=2.5.0=h27087fc_0
  - fontconfig=2.14.0=h8e229c2_0
  - freetype=2.10.4=h0708190_1
  - gcc=12.2.0=h26027b1_11
  - gcc_impl_linux-64=12.2.0=hcc96c02_19
  - gettext=0.21.1=h27087fc_0
  - glib=2.68.4=h9c3ff4c_1
  - glib-tools=2.68.4=h9c3ff4c_1
  - icu=64.2=he1b5a44_1
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h0b41bf4_3
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libdeflate=1.7=h7f98852_5
  - libffi=3.4.2=h6a678d5_6
  - libgcc-devel_linux-64=12.2.0=h3b97bd3_19
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.68.4=h174f98d_1
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.37=h21135ba_2
  - libsanitizer=12.2.0=h46fd767_19
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.3.0=hf544144_1
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - lz4-c=1.9.3=h9c3ff4c_1
  - ncurses=6.4=h6a678d5_0
  - nomkl=1.0=h5ca1d4c_0
  - numexpr=2.8.3=py37h85a3170_100
  - numpy=1.21.6=py37h976b520_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1t=h0b41bf4_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.3.5=py37h8c16a72_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=8.3.2=py37h0f21c89_0
  - pip=22.3.1=py37h06a4308_0
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycairo=1.21.0=py37h0afab05_1
  - python=3.7.16=h7a1cb2a_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytz=2022.7.1=pyhd8ed1ab_0
  - rdkit=2019.03.4=py37hb31dc5d_1
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.40.1=h5082296_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - networkx==2.6.3
    - torch==1.11.0+cu113
    - tqdm==4.64.1
    - typing-extensions==4.4.0
prefix: /scratch/user/yuning.you/.conda/envs/hiervae

