name: graph
channels:
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=1.3.0=py39h06a4308_0
  - aiohttp=3.8.3=py39h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - anyio=3.5.0=py39h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py39h06a4308_0
  - attrs=22.1.0=py39h06a4308_0
  - babel=2.11.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py39h06a4308_0
  - binutils_impl_linux-64=2.39=h6ceecb4_0
  - binutils_linux-64=2.39=h5fc0e48_11
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.4=py39h06a4308_0
  - brotlipy=0.7.0=py39h27cfd23_1003
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2023.5.7=hbcca054_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=h19f5f5c_2
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39h74dc2b5_0
  - click=8.0.4=py39h06a4308_0
  - comm=0.1.2=py39h06a4308_0
  - cryptography=39.0.1=py39h9ce1e76_0
  - cxx-compiler=1.0.0=hf484d3e_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dftd4=3.5.0=h03160e7_0
  - entrypoints=0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fontconfig=2.14.1=h52c9d5c_1
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py39h5eee18b_0
  - gcc=12.2.0=h26027b1_11
  - gcc_impl_linux-64=12.2.0=hcc96c02_19
  - gcc_linux-64=12.2.0=h4798a0e_11
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=h4ff587b_1
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - grpcio=1.42.0=py39hce63b2e_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gxx_impl_linux-64=12.2.0=hcc96c02_19
  - gxx_linux-64=12.2.0=hb41e900_11
  - htop=3.2.1=h0f457ee_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=4.11.3=py39h06a4308_0
  - ipykernel=6.19.2=py39hb070fc8_0
  - ipython=8.10.0=py39h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py39h06a4308_1
  - jinja2=3.1.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py39h06a4308_0
  - jupyter=1.0.0=py39h06a4308_8
  - jupyter_client=7.4.9=py39h06a4308_0
  - jupyter_console=6.6.2=py39h06a4308_0
  - jupyter_core=5.2.0=py39h06a4308_0
  - jupyter_server=1.23.4=py39h06a4308_0
  - jupyterlab=3.5.3=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.19.0=py39h06a4308_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - krb5=1.19.4=h568e23c_0
  - ld_impl_linux-64=2.39=hc81fddc_0
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=10.0.1=default_hb85057a_2
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-devel_linux-64=12.2.0=h3b97bd3_19
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm10=10.0.1=hbcb73fb_5
  - libnl=3.7.0=h166bdaf_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.20.3=he621ea3_0
  - libsanitizer=12.2.0=h46fd767_19
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-devel_linux-64=12.2.0=h3b97bd3_19
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.5.0=h6a678d5_2
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lxml=4.9.1=py39h1edc446_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown=3.4.1=py39h06a4308_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mctc-lib=0.3.1=h74f4db8_0
  - mistune=0.8.4=py39h27cfd23_1000
  - mmcif_pdbx=2.0.0=pyh44b312d_0
  - nbclassic=0.5.2=py39h06a4308_0
  - nbclient=0.5.13=py39h06a4308_0
  - nbconvert=6.5.4=py39h06a4308_0
  - nbformat=5.7.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py39h06a4308_0
  - notebook=6.5.2=py39h06a4308_0
  - notebook-shim=0.2.2=py39h06a4308_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - oauthlib=3.2.1=py39h06a4308_0
  - openbabel=3.1.1=py39hee2736e_2
  - openssl=1.1.1t=h0b41bf4_0
  - packaging=22.0=py39h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pdb2pqr=3.6.1=pyhd8ed1ab_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.0.1=py39h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=2.5.2=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - prometheus_client=0.14.1=py39h06a4308_0
  - prompt-toolkit=3.0.36=py39h06a4308_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - propka=3.5.0=py39hcca971b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py39h06a4308_0
  - pyopenssl=23.0.0=py39h06a4308_0
  - pyqt=5.15.7=py39h6a678d5_1
  - pyqt5-sip=12.11.0=py39h6a678d5_1
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.12=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py39h06a4308_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2022.7=py39h06a4308_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyzmq=23.2.0=py39h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtconsole=5.3.1=py39h06a4308_1
  - qtpy=2.2.0=py39h06a4308_0
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py39h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py39h06a4308_0
  - simple-dftd3=0.7.0=heafb486_2
  - sip=6.6.2=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py39h06a4308_1
  - soupsieve=2.3.2.post1=py39h06a4308_0
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tblite=0.3.0=h03160e7_0
  - tensorboard=2.11.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py39h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py39h06a4308_0
  - terminado=0.17.1=py39h06a4308_0
  - testpath=0.6.0=py39h06a4308_0
  - tinycss2=1.2.1=py39h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toml-f=0.3.1=h74f4db8_0
  - tomli=2.0.1=py39h06a4308_0
  - tornado=6.2=py39h5eee18b_0
  - traitlets=5.7.1=py39h06a4308_0
  - typing-extensions=4.4.0=py39h06a4308_0
  - typing_extensions=4.4.0=py39h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - websocket-client=0.58.0=py39h06a4308_4
  - werkzeug=2.2.2=py39h06a4308_0
  - wheel=0.38.4=py39h06a4308_0
  - widgetsnbextension=3.5.2=py39h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - anndata==0.9.2
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - autodocktools-py3==1.5.7.post1+3.gaee55d5
    - axial-positional-embedding==0.2.1
    - biopython==1.78
    - charset-normalizer==2.1.1
    - cmake==3.28.1
    - cmappy==4.0.1
    - colored-traceback==0.3.0
    - contextlib2==21.6.0
    - contourpy==1.0.6
    - cycler==0.11.0
    - dcor==0.6
    - deepspeed==0.5.9
    - dllogger==1.0.0
    - dm-tree==0.1.8
    - docker-pycreds==0.4.0
    - e3fp==1.2.5
    - e3nn==0.5.1
    - easydict==1.10
    - einops==0.6.0
    - exceptiongroup==1.1.3
    - fair-esm==2.0.0
    - fcd-torch==1.0.7
    - filelock==3.8.0
    - fonttools==4.38.0
    - fsspec==2022.11.0
    - functorch==0.1.0
    - geomloss==0.2.6
    - gitdb==4.0.10
    - gitpython==3.1.30
    - h5py==3.9.0
    - hjson==3.1.0
    - huggingface-hub==0.11.0
    - igraph==0.10.6
    - imageio==2.25.0
    - importlib-resources==5.12.0
    - iniconfig==2.0.0
    - ipdb==0.13.13
    - joblib==1.2.0
    - keopscore==2.1.2
    - kiwisolver==1.4.4
    - leidenalg==0.10.1
    - lightning-utilities==0.5.0
    - lit==17.0.6
    - llvmlite==0.40.1
    - lmdb==1.3.0
    - local-attention==1.4.4
    - markdown-it-py==3.0.0
    - matplotlib==3.7.1
    - mdurl==0.1.2
    - meeko==0.4.0
    - ml-collections==0.1.1
    - mmh3==3.0.0
    - molgrid==0.5.3
    - mpmath==1.2.1
    - msgpack==1.0.4
    - multidict==6.0.3
    - natsort==8.4.0
    - networkx==2.8.8
    - ninja==1.11.1
    - numba==0.57.1
    - numpy==1.23.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - omegaconf==2.3.0
    - openbabel-wheel==3.1.1.16
    - opt-einsum==3.3.0
    - opt-einsum-fx==0.1.4
    - pandas==1.5.2
    - pathtools==0.1.2
    - patsy==0.5.3
    - pillow==9.3.0
    - pluggy==1.3.0
    - pot==0.8.2
    - prefetch-generator==1.0.3
    - product-key-memory==0.1.10
    - protobuf==3.20.1
    - psutil==5.9.4
    - py-cpuinfo==9.0.0
    - py3dmol==2.0.1.post1
    - pyaml==21.10.1
    - pybind11==2.11.1
    - pygments==2.17.2
    - pygmtools==0.3.4
    - pykeops==2.1.2
    - pynndescent==0.5.10
    - pyparsing==3.0.9
    - pyquaternion==0.9.9
    - pytest==7.4.2
    - python-magic==0.4.27
    - pytorch-lightning==1.8.6
    - pyyaml==6.0
    - rdkit==2023.9.4
    - rdkit-pypi==2022.9.1
    - regex==2022.10.31
    - rich==13.7.0
    - scanpy==1.9.4
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - scprep==1.2.3
    - sdaxen-python-utilities==0.1.5
    - seaborn==0.12.2
    - sentry-sdk==1.15.0
    - session-info==1.0.0
    - setproctitle==1.3.2
    - sinkhorn-transformer==0.11.4
    - sklearn==0.0.post4
    - smart-open==6.3.0
    - smmap==5.0.0
    - statsmodels==0.14.0
    - stdlib-list==0.9.0
    - sympy==1.11.1
    - tensorboardx==2.5.1
    - termcolor==2.4.0
    - texttable==1.6.7
    - threadpoolctl==3.1.0
    - tokenizers==0.13.2
    - torch==1.11.0+cu113
    - torch-cluster==1.6.0
    - torch-ema==0.3
    - torch-geometric==2.1.0.post1
    - torch-scatter==2.0.9
    - torch-sparse==0.6.15
    - torchdiffeq==0.2.3
    - torchdrug==0.2.0.post1
    - torchmetrics==0.11.0
    - torchsde==0.2.6
    - torchvision==0.12.0
    - tqdm==4.64.1
    - trampoline==0.1.2
    - transformers==4.24.0
    - triton==2.0.0
    - umap-learn==0.5.3
    - urllib3==1.26.12
    - vina==1.2.3
    - wandb==0.13.10
    - wget==3.2
    - xtb==22.1
    - yarl==1.8.2
prefix: /scratch/user/yuning.you/.conda/envs/graph

