model:
  # checkpoint: ./pretrained_models/pretrained_diffusion.pt
  checkpoint: logs_diffusion/training_2023_11_15__21_36_00/checkpoints/56700.pt

sample:
  seed: 2021
  # num_samples: 100
  num_samples: 10
  num_steps: 1000
  pos_only: False
  center_pos_mode: protein
  sample_num_atoms: prior
